version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
    tty: true
    restart: always
    user: postgres
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    driver: local